import { CarWashProduct } from '@/types';

export const mockProducts: CarWashProduct[] = [
  // 1_휠/타이어
  {
    id: 'w1',
    name: '핫 림스 휠 클리너',
    brand: "Meguiar's",
    stepTag: '1_휠/타이어',
    description: '산성 성분 없이 강력하게 브레이크 더스트와 오염을 제거하는 휠 전용 클리너.',
    capacity: '709ml',
    recommended: true,
  },
  {
    id: 'w2',
    name: '타이어 드레싱',
    brand: 'Autoglym',
    stepTag: '1_휠/타이어',
    description: '타이어에 자연스러운 광택을 부여하고 갈라짐을 방지하는 드레싱.',
    capacity: '450ml',
    recommended: false,
  },
  {
    id: 'w3',
    name: '부스터 휠 클리너',
    brand: 'Chemical Guys',
    stepTag: '1_휠/타이어',
    description: '논산 pH 밸런스 포뮬러로 다양한 휠 소재에 안전하게 사용 가능.',
    capacity: '473ml',
    recommended: true,
  },
  {
    id: 'w4',
    name: 'Full Effect 휠 브러쉬',
    brand: 'Sonax',
    stepTag: '1_휠/타이어',
    description: '스포크 사이까지 닿는 유연한 나일론 브러쉬. 림과 타이어 동시 세척 가능.',
    recommended: false,
  },

  // 2_프리워시
  {
    id: 'p1',
    name: '퓨어 폼 스노우 폼',
    brand: 'Gyeon',
    stepTag: '2_프리워시',
    description: '거품이 차체 오염에 오래 밀착되어 프리워시 효과를 극대화하는 스노우 폼.',
    capacity: '1L',
    recommended: true,
  },
  {
    id: 'p2',
    name: 'Traffic Film Remover',
    brand: 'Auto Finesse',
    stepTag: '2_프리워시',
    description: '도로 위 기름때, 배기가스 오염물을 빠르게 분해하는 알칼리 TFR.',
    capacity: '500ml',
    recommended: false,
  },
  {
    id: 'p3',
    name: '타르 & 글루 리무버',
    brand: 'Bilt Hamber',
    stepTag: '2_프리워시',
    description: '도로 타르와 접착 잔여물을 도장면 손상 없이 안전하게 제거.',
    capacity: '500ml',
    recommended: true,
  },
  {
    id: 'p4',
    name: '버그 & 타르 리무버',
    brand: 'Sonax',
    stepTag: '2_프리워시',
    description: '전면부 곤충 잔여물과 타르를 빠르게 분해. 본세차 전 필수 사전 처리.',
    capacity: '500ml',
    recommended: false,
  },

  // 3_본세차
  {
    id: 'b1',
    name: 'Honeydew Snow Foam 샴푸',
    brand: 'Chemical Guys',
    stepTag: '3_본세차',
    description: '허니듀 향의 pH 중성 샴푸. 왁스·코팅 보호막을 유지하면서 세정.',
    capacity: '473ml',
    recommended: true,
  },
  {
    id: 'b2',
    name: 'Lather 카 샴푸',
    brand: 'Ritual Car Care',
    stepTag: '3_본세차',
    description: '풍부한 거품으로 미세 스크래치 없이 오염을 감싸 제거하는 고농축 샴푸.',
    capacity: '500ml',
    recommended: false,
  },
  {
    id: 'b3',
    name: 'Bodywork Shampoo',
    brand: 'Auto Finesse',
    stepTag: '3_본세차',
    description: '도장 보호 성분이 함유된 고급 카 샴푸. 세라믹 코팅 차량에도 안전.',
    capacity: '1L',
    recommended: true,
  },
  {
    id: 'b4',
    name: '차량용 워시 미트',
    brand: 'Koch Chemie',
    stepTag: '3_본세차',
    description: '극세사 파일이 오염을 안전하게 흡착. 와이어링 방지 구조 설계.',
    recommended: false,
  },

  // 4_드라잉
  {
    id: 'd1',
    name: 'Hi-Tech Drying Towel',
    brand: 'Autoglym',
    stepTag: '4_드라잉',
    description: '초흡수 극세사 소재로 대형 차량도 한 장으로 완벽하게 드라잉.',
    capacity: '60×90cm',
    recommended: true,
  },
  {
    id: 'd2',
    name: 'Silk Dryer 타올',
    brand: 'Chemical Guys',
    stepTag: '4_드라잉',
    description: '실크같이 부드러운 터치로 잔기스 걱정 없는 초극세사 드라잉 타올.',
    capacity: '56×76cm',
    recommended: false,
  },
  {
    id: 'd3',
    name: 'FEN 에어 블로어',
    brand: 'Ryme',
    stepTag: '4_드라잉',
    description: '도어 트림·미러·엠블럼 틈새 물기를 완전 제거하는 휴대용 에어 블로어.',
    recommended: true,
  },
  {
    id: 'd4',
    name: '워터 블레이드',
    brand: 'Sonax',
    stepTag: '4_드라잉',
    description: '실리콘 블레이드로 대형 패널 물기를 빠르게 쓸어내는 드라잉 보조 도구.',
    recommended: false,
  },

  // 5_코팅/마무리
  {
    id: 'c1',
    name: 'Ceramic Spray Coating',
    brand: 'Autoglym',
    stepTag: '5_코팅/마무리',
    description: '세라믹 성분이 도장면에 발수·광택 보호막을 형성. 최대 3개월 지속.',
    capacity: '250ml',
    recommended: true,
  },
  {
    id: 'c2',
    name: 'Ultimate Quik Detailer',
    brand: "Meguiar's",
    stepTag: '5_코팅/마무리',
    description: '세차 후 마무리에 최적. 빠른 광택과 소수성을 동시에 부여.',
    capacity: '709ml',
    recommended: true,
  },
  {
    id: 'c3',
    name: 'Butter Wet Wax',
    brand: 'Chemical Guys',
    stepTag: '5_코팅/마무리',
    description: '카르나우바 성분의 딥글로스 왁스. 도장면에 깊은 광택과 습식 광을 연출.',
    capacity: '473ml',
    recommended: false,
  },
  {
    id: 'c4',
    name: 'Brilliant Shine Detailer',
    brand: 'Sonax',
    stepTag: '5_코팅/마무리',
    description: '발수 효과와 광택을 빠르게 복원. 코팅 차량 탑업 제품으로 최적.',
    capacity: '750ml',
    recommended: false,
  },
];
