import { CarWashProduct } from '@/types';

export const mockProducts: CarWashProduct[] = [
  // 1_휠/타이어
  {
    id: 'w1',
    name: '불스원 크리스탈 휠크리너',
    brand: '불스원',
    stepTag: '1_휠/타이어',
    description: '국내 온라인몰에서 쉽게 찾을 수 있는 휠 전용 클리너. 브레이크 분진과 일반 오염 제거용.',
    capacity: '600ml',
    recommended: true,
    source: 'fallback',
  },
  {
    id: 'w2',
    name: '글로스브로 타이어 코팅제',
    brand: '글로스브로',
    stepTag: '1_휠/타이어',
    description: '셀프세차장에서 많이 쓰이는 타이어 광택/코팅 계열 제품.',
    capacity: '500ml',
    recommended: false,
    source: 'fallback',
  },
  {
    id: 'w3',
    name: '마프라 휠앤타이어 클리너',
    brand: '마프라',
    stepTag: '1_휠/타이어',
    description: '휠과 타이어 오염을 함께 다루는 세정제. 국내 디테일링 쇼핑몰에서 유통되는 제품군.',
    capacity: '500ml',
    recommended: true,
    source: 'fallback',
  },
  {
    id: 'w4',
    name: '잇츠윈 휠 브러쉬',
    brand: '잇츠윈',
    stepTag: '1_휠/타이어',
    description: '스포크 안쪽과 림 틈새를 닦기 위한 휠 전용 브러쉬.',
    recommended: false,
    source: 'fallback',
  },

  // 2_프리워시
  {
    id: 'p1',
    name: '글로스브로 버블밤 프리워시',
    brand: '글로스브로',
    stepTag: '2_프리워시',
    description: '폼랜스와 함께 쓰기 좋은 프리워시/스노우폼 계열 제품.',
    capacity: '500ml',
    recommended: true,
    source: 'fallback',
  },
  {
    id: 'p2',
    name: '파이어볼 프리워시',
    brand: '파이어볼',
    stepTag: '2_프리워시',
    description: '국내 디테일링 브랜드의 사전 세정 제품군. 본세차 전 오염 완화용.',
    capacity: '500ml',
    recommended: false,
    source: 'fallback',
  },
  {
    id: 'p3',
    name: '불스원 타르 제거제',
    brand: '불스원',
    stepTag: '2_프리워시',
    description: '도로 타르와 끈적한 오염을 제거하기 위한 전처리 제품.',
    capacity: '500ml',
    recommended: true,
    source: 'fallback',
  },
  {
    id: 'p4',
    name: '소낙스 버그 리무버',
    brand: '소낙스',
    stepTag: '2_프리워시',
    description: '전면부 벌레 자국 제거에 쓰이는 국내 판매 제품군.',
    capacity: '500ml',
    recommended: false,
    source: 'fallback',
  },

  // 3_본세차
  {
    id: 'b1',
    name: '불스원 크리스탈 카샴푸',
    brand: '불스원',
    stepTag: '3_본세차',
    description: '대중적으로 구매 가능한 카샴푸. 기본 버킷 세차용으로 적합.',
    capacity: '500ml',
    recommended: true,
    source: 'fallback',
  },
  {
    id: 'b2',
    name: '글로스브로 오렌지크러쉬 카샴푸',
    brand: '글로스브로',
    stepTag: '3_본세차',
    description: '국내 셀프세차 사용자층에서 인지도가 있는 카샴푸 제품군.',
    capacity: '500ml',
    recommended: false,
    source: 'fallback',
  },
  {
    id: 'b3',
    name: '파이어볼 타론 카샴푸',
    brand: '파이어볼',
    stepTag: '3_본세차',
    description: '디테일링 작업에서 쓰이는 pH 중성 샴푸 계열 제품.',
    capacity: '500ml',
    recommended: true,
    source: 'fallback',
  },
  {
    id: 'b4',
    name: '잇츠윈 워시미트',
    brand: '잇츠윈',
    stepTag: '3_본세차',
    description: '차체 접촉 세척용 극세사 워시미트.',
    recommended: false,
    source: 'fallback',
  },

  // 4_드라잉
  {
    id: 'd1',
    name: '퓨어스타 트위스트 드라잉타월',
    brand: '퓨어스타',
    stepTag: '4_드라잉',
    description: '국내 세차용품 시장에서 흔히 판매되는 대형 드라잉타월.',
    capacity: '70×90cm',
    recommended: true,
    source: 'fallback',
  },
  {
    id: 'd2',
    name: '잇츠윈 드라잉타월',
    brand: '잇츠윈',
    stepTag: '4_드라잉',
    description: '도장면 물기 제거용 극세사 드라잉 타월.',
    capacity: '70×90cm',
    recommended: false,
    source: 'fallback',
  },
  {
    id: 'd3',
    name: '카렉스 드라잉 타월',
    brand: '카렉스',
    stepTag: '4_드라잉',
    description: '오프라인/온라인에서 접근성이 높은 차량용 드라잉 타월 제품군.',
    recommended: true,
    source: 'fallback',
  },
  {
    id: 'd4',
    name: '차량용 에어건 송풍기',
    brand: '공용',
    stepTag: '4_드라잉',
    description: '미러, 그릴, 엠블럼 틈새 물기 제거용 드라잉 보조 도구.',
    recommended: false,
    source: 'fallback',
  },

  // 5_코팅/마무리
  {
    id: 'c1',
    name: '불스원 크리스탈 코트 플러스',
    brand: '불스원',
    stepTag: '5_코팅/마무리',
    description: '국내에서 쉽게 구매 가능한 스프레이 코팅/물왁스 계열 제품.',
    capacity: '500ml',
    recommended: true,
    source: 'fallback',
  },
  {
    id: 'c2',
    name: '더클래스 불렛 타이거 물왁스',
    brand: '더클래스',
    stepTag: '5_코팅/마무리',
    description: '세차 후 발수와 광택 보강에 쓰이는 국내 판매 물왁스 제품군.',
    capacity: '500ml',
    recommended: true,
    source: 'fallback',
  },
  {
    id: 'c3',
    name: '파이어볼 쇼카왁스',
    brand: '파이어볼',
    stepTag: '5_코팅/마무리',
    description: '도장면 광택과 보호막 보강을 위한 왁스 계열 제품.',
    capacity: '100g',
    recommended: false,
    source: 'fallback',
  },
  {
    id: 'c4',
    name: '소낙스 브릴리언트 샤인 디테일러',
    brand: '소낙스',
    stepTag: '5_코팅/마무리',
    description: '국내 판매되는 퀵디테일러. 세차 후 발수와 광택 보강용.',
    capacity: '750ml',
    recommended: false,
    source: 'fallback',
  },
];
